CREATE DATABASE LIBRARY;

USE LIBRARY;

CREATE TABLE BRANCH ( BRANCH_NO INT PRIMARY KEY, MANAGER_ID INT, BRANCH_ADDRESS VARCHAR (255), CONTACT_NO VARCHAR (15));

INSERT INTO BRANCH VALUES (1, 101,"CALICUT", 444333);
INSERT INTO BRANCH VALUES (8, 109,"CALICUT", 444333);
INSERT INTO BRANCH VALUES (2,102,"TRIVANDRUM",444888);
INSERT INTO BRANCH VALUES (3,103,"MALAPRM",444111);
INSERT INTO BRANCH VALUES (4,104,"THRSURE",444555);
INSERT INTO BRANCH VALUES (5,105,"KOCHI",444666);
INSERT INTO BRANCH VALUES (6,106,"MALAPRM",444999);
INSERT INTO BRANCH VALUES (7,107,"THRSURE",444777);

select * FROM BRANCH;

CREATE TABLE EMPLOYEE1( EMPLOYEE_ID INT PRIMARY KEY, EMPLOYEE_NAME VARCHAR(30), POSITION VARCHAR (30), SALARY FLOAT (15));

INSERT INTO  EMPLOYEE1 VALUES (101,"MANEESHA","MANAGER",50000);
INSERT INTO  EMPLOYEE1 VALUES (102,"NAVAS","DIGITA MARKETIN",25000);
INSERT INTO  EMPLOYEE1 VALUES (103,"SHIYAS","HR",30000);
INSERT INTO  EMPLOYEE1 VALUES (104,"SHAZIYA","MARKETING",25000);
INSERT INTO  EMPLOYEE1 VALUES (105,"RASHEEL","ACCOUNTANT",20000);
INSERT INTO  EMPLOYEE1 VALUES (109,"MANU","DESIGNER",40000);
CREATE TABLE CUSTOMER (CUSTOMER_ID INT PRIMARY KEY, CUSTMER_NAME VARCHAR (30), CUSTOMER_ADDRESS VARCHAR (30), REG_DATE DATE );

INSERT INTO  CUSTOMER VALUES (223,"NISAM","XXX","2022-01-15");
INSERT INTO  CUSTOMER VALUES (224,"JAZEEL","YYY","2022-02-23");
INSERT INTO  CUSTOMER VALUES (225,"AKHIL","ZZZ","2020-03-12");
INSERT INTO  CUSTOMER VALUES (226,"ANWER","AAA","2023-04-06");
INSERT INTO  CUSTOMER VALUES (227,"BUFEENA","BBB","2023-01-01");
INSERT INTO  CUSTOMER VALUES (228,"ASHIQ","DDD","2020-01-15");

SELECT* FROM CUSTOMER;


CREATE TABLE ISSUESATATUS( ISSUE_ID INT PRIMARY KEY, ISSUED_CUST INT, ISSUED_BOOKNAME VARCHAR (30), ISSUE_DATE DATE, 
ISBN_BOOK VARCHAR (30), foreign key (ISSUED_CUST) references CUSTOMER (CUSTOMER_ID), foreign key (ISBN_BOOK) references BOOKS(ISBN));

INSERT INTO ISSUESATATUS VALUES  (001,223,"BOOK A","2023-01-20","ISBN-001");
INSERT INTO ISSUESATATUS VALUES  (002,224,"BOOK B","2023-02-20","ISBN-002");
INSERT INTO ISSUESATATUS VALUES  (003,225,"BBOK C","2023-06-20","ISBN-003");

SELECT * FROM ISSUESATATUS;

CREATE TABLE RETURNSTATUS (RETURN_ID INT PRIMARY KEY, RETURN_CUSTOMER INT, RETURN_BOOKNAME VARCHAR (30), RETURN_DATE DATE,
 ISBN_BOOK2 VARCHAR(30), foreign key (RETURN_CUSTOMER ) references CUSTOMER(CUSTOMER_ID), 
 foreign key (ISBN_BOOK2) references BOOKS(ISBN));
 
 
 INSERT INTO RETURNSTATUS VALUES(2,225,"BOOK C","2023-7-01","ISBN-003");
  
  SELECT * FROM RETURNSTATUS;
  
 CREATE TABLE BOOKS(ISBN VARCHAR (40) PRIMARY KEY, BOOK_TITLE VARCHAR (30), CATEGORY VARCHAR (30),
 RENTAL_PRICE FLOAT(15),STATUS VARCHAR(10),
 AUTHOR VARCHAR (30), PUBLISHER  VARCHAR (30));
 
 INSERT INTO BOOKS VALUES ("ISBN-001","BOOK A","FICTION",10,"NO", "BASHEER","ABC");
 INSERT INTO BOOKS VALUES ("ISBN-002","BOOK B","CRIME THRLER",10,"YES", "KHALID HUSSAINI","ABC");
 INSERT INTO BOOKS VALUES ("ISBN-003","BOOK C","HISTORY",10,"YES", "BENNYAMIN","DC");
 
 SELECT* FROM BOOKS;
 
 
 #Q1: RETRIEVE THE BOOK TITLE, CATEGORY AND RENTAL PRICE
 
 SELECT BOOK_TITLE,CATEGORY,RENTAL_PRICE FROM BOOKS WHERE STATUS= "YES";
 
 #Q2 List the employee names and their respective salaries in descending order of salary.
 

SELECT EMPLOYEE_NAME, SALARY FROM EMPLOYEE1 ORDER BY SALARY DESC;

#Q3 Retrieve the book titles and the corresponding customers who have issued those books.


SELECT BOOK_TITLE, CUSTMER_NAME FROM BOOKS JOIN ISSUESATATUS ON ISBN = ISBN_BOOK JOIN CUSTOMER ON ISSUED_CUST= CUSTOMER_ID;

#Q4 Display the total count of books in each category. 

SELECT CATEGORY, COUNT(*)  AS TOTAL_COUNT FROM BOOKS GROUP BY CATEGORY;

#Q5Retrieve the employee names and their positions for the employees whose salaries are above Rs.40000.
 

SELECT EMPLOYEE_NAME, POSITION FROM EMPLOYEE1 WHERE SALARY > 40000;

#Q6  List the customer names who registered before 2022-01-01 and have not issued any books yet. 


SELECT CUSTMER_NAME FROM CUSTOMER WHERE REG_DATE <"2022-01-01" AND CUSTOMER_ID NOT IN (SELECT ISSUED_CUST FROM ISSUESATATUS);

#Q7 Display the branch numbers and the total count of employees in each branch. 
 

SELECT BRANCH_NO , COUNT(EMPLOYEE_ID ) FROM BRANCH LEFT JOIN EMPLOYEE1 ON  MANAGER_ID=EMPLOYEE_ID GROUP BY BRANCH_NO;

#Q8  Display the names of customers who have issued books in the month of June 2023.


SELECT CUSTMER_NAME FROM CUSTOMER INNER JOIN ISSUESATATUS ON CUSTOMER_ID = ISSUED_CUST WHERE MONTH (ISSUE_DATE) = 6
AND YEAR (ISSUE_DATE)=2023;

#Q9 Retrieve book_title from book table containing history. 

SELECT BOOK_TITLE FROM BOOKS WHERE CATEGORY="HISTORY";


#Q10. Retrieve the branch numbers along with the count of employees for branches having more than 5 employees. 

SELECT BRANCH_NO, COUNT(EMPLOYEE_ID) AS TOTAL_EMPLOYEES FROM BRANCH INNER JOIN
 EMPLOYEE1 ON MANAGER_ID= EMPLOYEE_ID GROUP BY BRANCH_NO HAVING count(EMPLOYEE_ID)>5;
